version: "3.8"
services:
  db:
    image: mysql:9.0.1
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: WaletTrans
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "bash", "-c", "mysqladmin ping -h localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      timeout: 5s

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ".:/rails"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: WaletTrans
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      REDIS_URL: redis://redis:6379

volumes:
  db_data:
    driver: local
